server:
  port: ${PORT:9999}
  context-path: ${CONTEXTPATH:/spring-boot}

spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/zk?useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456